# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: device-quality-control-plugin-requirements
{% if GIT_DESCRIBE_NUMBER > '0' %}
  version: {{ GIT_DESCRIBE_TAG[1:] }}.post{{ GIT_DESCRIBE_NUMBER }}
{% else %}
  version: {{ GIT_DESCRIBE_TAG[1:] }}
{% endif %}

requirements:
  build:
    - dmf-control-board-firmware >=1.5.0
    - matplotlib
    - microdrop >=2.4
    - microdrop-plugin-manager >=0.11
    - pandas
    - path_helpers >=0.2.post3
    - svg-model >=0.5.post20
    - wheeler.pygtkhelpers >=0.13.post17
    - zmq-plugin >=0.2.post2

  run:
    - dmf-control-board-firmware >=1.5.0
    - matplotlib
    - microdrop >=2.4
    - microdrop-plugin-manager >=0.11
    - pandas
    - path_helpers >=0.2.post3
    - svg-model >=0.5.post20
    - wheeler.pygtkhelpers >=0.13.post17
    - zmq-plugin >=0.2.post2

about:
  home: http://github.com/wheeler-microfluidics/device_quality_control_plugin
  license: BSD
